### ISSUE TITLE
The Mod have 3 Bugs

### ISSUE THREAD

**Issue by Titoo8899** [liray-dev/Dynamic-Ambience-And-Music#1]
Hi,
I have 3 Bugs found in your mod.

The First is a Music Work not Bug.
I have 2 Music have I first as MP3 Download and then to a OGG Data make and place in her mod.
1 Link: https://www.youtube.com/watch?v=7CHhUvUKHJc
2 Link: https://www.youtube.com/watch?v=62O3afJK4aM&list=PLKOndF8nj42fGESaQanpWnFnKNELFo0-7&index=14
This 2 Musics have I add and have on a Area of 5X5X5 Blocks the Sounds start. But the Music work not and play not. Please fix it.

The Second Bug is a Bug of the Sound Block in your mod. I can not Place it on the ground. The Block have from self destroyed her functions for Place on the Ground. I hope you can fix it.

And the last Bug is bad for all worlds. I can in the Area what I have set no normal Blocks etc. place. I mean then can the Block destroy in the area but I can not place a new Block. I hope you can fix it.

I have all Data Clear and new make but with the same problem.

**Comment by liray-dev** [comment]
Bro.. 


1) After downloading the sounds, you need to press F3 + T
This will reload minecraft resources and load sounds.json
2) Read the descriptions of the items. 
Blocks are hidden from view by default, you need an item to enable them. For light, Rod of Light. And for sound - Sound Block Editor

**Comment by Titoo8899** [comment]
I have check and okay the second of your thinks is right and work but the F3+T reload the mc resources but the sounds will not play
