### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by Theundercow** [liray-dev/Dynamic-Ambience-And-Music#2]
Seems that the mod is causing a crash on server side only. Works on client with exact same mod pack installed. Could be an issue with mohist or a plugin? These are the only things different between my client and server. Hopefully the issue can be fixed your mod is perfect for me and I love its ease of use. Great work either way, keep it up!

[crash-2024-07-09_23.18.21-server.txt](https://github.com/user-attachments/files/16152081/crash-2024-07-09_23.18.21-server.txt)

**Comment by liray-dev** [comment]
fixed!
